### ISSUE TITLE
can you add 6-fold train and test code?

### ISSUE THREAD

**Issue by mmiku1** [hancyran/RepSurf#10]
Hello,I tried to reproduce the experimental results in your paper,My results are similar to those in your paper in Area5, but I want to try the experimental results in 6-fold.
if you can provide the code,I would be grateful！
thx

**Comment by hancyran** [comment]
It could be quite simple. You just need to change the option --test_area in [https://github.com/hancyran/RepSurf/blob/main/segmentation/scripts/s3dis/train_repsurf_umb.sh#L17](url). By default, test_area is 5 (it means you train a model on S3DIS Area 5). So you just need to run the script with different test_area options (1~6), and average miou of each result to get the 6-fold performance.

**Comment by mmiku1** [comment]
thx.
I know this method, but that means I need 6 train.Is the data of 6-fold experiments in your paper in this way?

**Comment by hancyran** [comment]
Correct. We follow the common protocal of [PointNet](https://arxiv.org/pdf/1612.00593.pdf).

**Comment by mmiku1** [comment]
Your answer has solved my question. I wish you a happy life and smooth scientific research！

**Comment by mmiku1** [comment]
Your answer has solved my question and wish you a good life

**Comment by hancyran** [comment]
Thanks for your interest in our work, and best wishes to you.
