### ISSUE TITLE
few question: how do i train this code 6-fold on s3dis dataset.

### ISSUE THREAD

**Issue by ybc-ybc** [hancyran/RepSurf#12]
sorry, I just saw the s3dis area-5 result. how can i train this code for S3DIS 6-fold?

Another question： I see this code to feed too much point clouds into the network. If the input point cloud data will be reduced, speeding up training.
Will this cause a drop in accuracy?

**Comment by hancyran** [comment]
Thanks for your interest in our work.
1st question: please refer to [this issue](https://github.com/hancyran/RepSurf/issues/10)
2nd question: Correct. we had some experiments showing that when we increase the voxel size of grid sampling (#points be reduced), there would be a drop in performance.

**Comment by ybc-ybc** [comment]
> Thanks for your interest in our work. 1st question: please refer to [this issue](https://github.com/hancyran/RepSurf/issues/10) 2nd question: Correct. we had some experiments showing that when we increase the voxel size of grid sampling (#points be reduced), there would be a drop in performance.

Thank you for your answer and wish you a happy life！
