### ISSUE TITLE
How to train and evaluate the model on multiple GPUs？

### ISSUE THREAD

**Issue by zheng0819** [hancyran/RepSurf#14]
hello, I try to train the model on two gpus, but an error occurred. The error occurred when load the S3DIS dataset. The error shows that "ValueError: batch_size should be a positive integer value, but got batch_size=0", how can I solve this problem?  Thanks for your help.

**Comment by hancyran** [comment]
Can you provide more details about it? This may occur when you train to use very small batch_size, like batch_size=1 when you have two gpus. As the code performs a DDP training, the batch_size should be divisible by the num of gpus. Like you have to set batch_size=2N in the script if you use two gpus.

**Comment by zheng0819** [comment]
Thanks for your help! I will try to change the batch_size later. And I think your work is really impressive. I'm trying to use the idea of AdaptConv to Repsurf, the efficient representation of point cloud makes me think a lot. Thanks again!

在2022-11-02 10:20:18，Haoxi ***@***.***写道：

Can you provide more details about it? This may occur when you train to use very small batch_size, like batch_size=1 when you have two gpus. As the code performs a DDP training, the batch_size should be divisible by the num of gpus. Like you have to set batch_size=2N in the script if you use two gpus.

**Comment by zheng0819** [comment]
Changing batch_size makes sense, thank you!

**Comment by hancyran** [comment]
Thanks for your support! And I will close the issue.
