### ISSUE TITLE
Backbone for segmentation

### ISSUE THREAD

**Issue by tranganhthuan** [hancyran/RepSurf#2]
Hi, thank you for your great work. I have read your paper and I am curious about the backbone of the segmentation task. Do you use the same Decoder of PointNet++ or have any modifications on it?

**Comment by hancyran** [comment]
Sorry for the late reply. 

We have uploaded the segmentation backbone in the "segmentation" folder as well as the pretrained models and the logs. Please feel free to check and use it! I will close the issue.

Thank you again for your interest in our work!
