### ISSUE TITLE
Export RepSurf to ONNX fails

### ISSUE THREAD

**Issue by jelenab98** [hancyran/RepSurf#23]
Hi, 
thank you for the great work and code!

I want to deploy a RepSurf model and to do that I need the model in ONNX format. It seems that the conversion to ONNX fails due to custom pointops kernels. Have you ever encountered this and perhaps have any advice?

Thanks, 
Jelena

**Comment by hancyran** [comment]
Thanks for your support! I am sorry I did not ever convert the models into ONNX format, and I am not sure which specific task you are focusing on, but if you wanna use the pytorch model in tensorflow or so, you could consider manually storing the pretrained weights from the dict after loading the .pth files. Then, you need to load the weights into the modules (like nn.conv or nn.linear) of the DL lib you would like to use in a compatible way. The custom pointops kernels work for data/feature processing, so they are sperate from these learnable modules, but if you do not use pytorch lib, you may have to rewrite these kernels to ensure a similar process.

For classification, you could remove the flag "--cuda_ops" to replace the custom kernels with pure pytorch version. But for segmentation, you have to use the kernels for grid sampling.

**Comment by jelenab98** [comment]
Hi, 
thanks for the answer. I want to run the inference on segmentation task from the C++. I thought that the cleanest way is to convert the model to ONNX and then just invoke the forward pass from the C++ script but ONNX has some troubles with custom cuda kernels.

**Comment by hancyran** [comment]
I am not familiar with ONNX lib, but I think it would be a good news to rewrite the kernels as the kernel files (.cu) are written in a style very similar to c++. Maybe you can try working on it.

**Comment by jelenab98** [comment]
Will look into it. Thanks!

**Comment by hancyran** [comment]
Thanks for your support! I will close the issue
