### ISSUE TITLE
When will you update the code of Segmentation on S3DIS / ScanNet？

### ISSUE THREAD

**Issue by Qinerrrrr** [hancyran/RepSurf#3]
您的工作非常出色，请问什么时候可以更新一下有关室内数据集s3dis和scannetv2的代码呢？

**Comment by hancyran** [comment]
Sorry for the late reply.

We have uploaded the segmentation backbone in the "segmentation" folder as well as the pretrained models and the logs. Please feel free to check and use it! I will close the issue.

Thank you again for your interest in our work! 感谢你的关注，祝好！
