### ISSUE TITLE
Where can I find "lib/pointops"?

### ISSUE THREAD

**Issue by JiachengDeng** [hancyran/RepSurf#6]
When I want to configure the environment, I find I can't find the folder ‘lib/pointops’, where can I download the relevant file and configure it?
☆⌒(*＾-゜)v THX!!

**Comment by JiachengDeng** [comment]
We can use part of the library [pointops] from (https://github.com/hszhao/PointWeb/tree/master/lib/pointops)[PointTransformer](https://github.com/POSTECH-CVLab/point-transformer) or [PointWeb](https://github.com/hszhao/PointWeb).

**Comment by hancyran** [comment]
It seems I did not commit pointops lib with git. 

This can be an option. And I have uploaded the pointops lib in the current repo. You can see the changes here (https://github.com/hancyran/RepSurf/commit/3e4aa3bd491c69b8ba0357d811302a816cb78dc6).

> We can use part of the library [pointops](https://github.com/hszhao/PointWeb/tree/master/lib/pointops) from [PointTransformer](https://github.com/POSTECH-CVLab/point-transformer) or [PointWeb](https://github.com/hszhao/PointWeb).

**Comment by JiachengDeng** [comment]
Thank you so much, this works for me.
