### ISSUE TITLE
[Seg. Pointops Compile] name "pointops_cuda" conflicts with Cls. Pointops

### ISSUE THREAD

**Issue by Margaretya** [hancyran/RepSurf#8]
Dear authors,
Thank you so much for your awesome work. 

When I follow your source code to compile Pointops in Classification and then compile the other Pointops in Segmentation, the Pointops imported will come from Cls.'s. 

This problem was found by 
```
File './RepSurf/segmentation/modules/pointops/functions/pointops.py', line 126, in forward
    pointops_cuda.knnquery_cuda(m, nsample, xyz, new_xyz, offset, new_offset, idx, dist2)
TypeError: knnquery_cuda(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: int, arg2: int, arg3: int, arg4: at::Tensor, arg5: at::Tensor, arg6: at::Tensor, arg7: at::Tensor) -> None
```

Since knnquery_cuda() in Seg.'s Pointops support  `(arg0: int, arg1: int, arg2: at::Tensor, arg3: at::Tensor, arg4: at::Tensor, arg5: at::Tensor, arg6: at::Tensor, arg7: at::Tensor)`.

Then I found `setup(
    name='pointops',
    ext_modules=[
        CUDAExtension('pointops_cuda',` in [ Cls's Pointops](https://github.com/hancyran/RepSurf/blob/main/classification/modules/pointops/setup.py) and 
`setup(
    name='pointops_cuda',
    ext_modules=[
        CUDAExtension('pointops_cuda',` in [ Seg's Pointops](https://github.com/hancyran/RepSurf/blob/main/segmentation/modules/pointops/setup.py). They have different python site-packages names but the same CUDAExtension name. This may cause upon problems during `import pointops_cuda`. 

Because I am not familiar with C++, would you help me solve this problem?
(The solution for now on is to delete the other site-packages while using one)

Thanks again for your great work.

**Comment by hancyran** [comment]
Thank you for your interest in our work.

This is the conflict of cuda extensions. A simple way to solve it is to follow our init.sh scripts to create two different conda envs for the two tasks (for [cls](https://github.com/hancyran/RepSurf/blob/main/classification/init.sh) and [seg](https://github.com/hancyran/RepSurf/blob/main/segmentation/init.sh)). 

There is another way but it might be a bit complex - you need to compile the cuda extensions locally. By default, we use the command  **python3 setup.py install** to install pointops globally. To install it locally, you need to use **python setup.py build_ext --inplace** instead. Accordingly, you also need to import pointops extension locally by replacing **Line 7-28** in [pointops.py](https://github.com/hancyran/RepSurf/blob/main/segmentation/modules/pointops/functions/pointops.py#L7) with **from .. import pointops_cuda**.

Hope these could help.

**Comment by Margaretya** [comment]
Thank you, your suggestions are helpful. We found that changing one CUDAExtension name and recompiling, then replacing all `pointops_cuda` in [pointops.py](https://github.com/hancyran/RepSurf/blob/main/segmentation/modules/pointops/functions/pointops.py) with the new name will also work.
