### ISSUE TITLE
When will you publish codes about scannetv2?

### ISSUE THREAD

**Issue by YehLi** [hancyran/RepSurf#9]
When will you publish codes about scannetv2?

**Comment by hancyran** [comment]
If necessary, we will publish it with the pretrained weights soon.

However, if you can't wait for it, it could be quite simple to implement the experiment on scannet, as we have already provided the scannet options in the [train.py](https://github.com/hancyran/RepSurf/blob/main/segmentation/tool/train.py#L457). You just need to replace the value of [option --dataset](https://github.com/hancyran/RepSurf/blob/main/segmentation/scripts/s3dis/train_repsurf_umb.sh#L7) with ScanNet_train (to train on training dataset and eval on validation dataset) or ScanNet_trainval (to train on the combo of training and validation datasets). For the preprocessed data, we could provide a [google drive link](https://drive.google.com/file/d/1I6Kl4XCJVBPbk4C-i1Dkg5yP2h9Ss542/view?usp=sharing) in advance, but you need to write a ScanNet dataloader similar to the [S3DIS dataloader](https://github.com/hancyran/RepSurf/blob/main/segmentation/dataset/S3DISDataLoader.py).

**Comment by YehLi** [comment]
Thanks for your reply. How many gpus do you utilize for training on scannetv2?

**Comment by hancyran** [comment]
We use 4 gpus for training here.
